name: CI Workflow
on: [push, pull_request]

jobs:
  test_application:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code into the Go module directory
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version-file: 'go.mod'

      - name: Run tests
        run: go test -v -cover ./...
  
  govulncheck:
    runs-on: ubuntu-latest
    name: Run govulncheck
    steps:
      - name: Checkout code into the Go module directory
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version-file: 'go.mod'

      - name: Running Vulnerability Check
        run: |
          go install golang.org/x/vuln/cmd/govulncheck@latest
          govulncheck ./...
