package main

import (
	"fmt"
	"os"
	"os/signal"
	"path/filepath"
	"syscall"
)

// anchorFile is named for what a leftover would be: if a run is killed where no
// cleanup can reach it, the name has to say where the file came from.
const anchorFile = "goswag_module_anchor.go"

const anchorSource = `// Code generated by goswag while it ran swag; it is deleted when swag is done.
// A module root with no Go file of its own makes ` + "`go list`" + ` fail there, and swag
// then falls back to relative import paths, reads each package a second time
// under its real path, and takes every type for a name collision with itself.
package goswagmoduleanchor
`

// anchorModuleRoot gives swag a directory go list can name. It reports whether
// it wrote anything, so a directory that already has Go files is left untouched.
func anchorModuleRoot(dir string) (cleanup func(), err error) {
	populated, err := hasGoFile(dir)
	if err != nil || populated {
		return func() {}, err
	}

	path := filepath.Join(dir, anchorFile)
	if err := os.WriteFile(path, []byte(anchorSource), 0o600); err != nil {
		return func() {}, fmt.Errorf("writing the module anchor at %s: %w", path, err)
	}

	stop := removeOnSignal(path)

	var once bool
	return func() {
		if once {
			return
		}
		once = true
		stop()
		os.Remove(path)
	}, nil
}

func hasGoFile(dir string) (bool, error) {
	entries, err := os.ReadDir(dir)
	if err != nil {
		return false, fmt.Errorf("reading %s: %w", dir, err)
	}

	for _, entry := range entries {
		if !entry.IsDir() && filepath.Ext(entry.Name()) == ".go" {
			return true, nil
		}
	}
	return false, nil
}

// removeOnSignal covers the one exit a deferred cleanup cannot: an interrupt
// while swag is running would otherwise leave the file in the user's repository.
func removeOnSignal(path string) (stop func()) {
	signals := make(chan os.Signal, 1)
	signal.Notify(signals, os.Interrupt, syscall.SIGTERM)

	done := make(chan struct{})
	go func() {
		select {
		case sig := <-signals:
			os.Remove(path)
			signal.Stop(signals)
			// Exit the way the signal would have, so a caller waiting on this
			// process still sees it was interrupted.
			if process, err := os.FindProcess(os.Getpid()); err == nil {
				signal.Reset(sig.(syscall.Signal))
				_ = process.Signal(sig)
			}
		case <-done:
		}
	}()

	return func() {
		signal.Stop(signals)
		close(done)
	}
}
